name: pengelolaan_keuangan_masjid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  pdf: ^3.10.8
  printing: ^5.12.0
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite_common_ffi: ^2.3.3
  ffi: ^2.1.2
  sqlite3_flutter_libs: ^0.5.24
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/masjid.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/masjid.png
    - assets/keuangan.png
    - assets/user.png
    - assets/slider/
    - assets/fonts/